# Generated by Django 5.0.4 on 2024-04-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrados',
            new_name='Registrado',
        ),
    ]
